[package]
name = "minesweeper"
version = "0.0.1"
authors = ["John Foley <john@hisfoleyness.com>"]

[dependencies]
rand = "0.3"

[dependencies.ncurses]
link = "/usr/local/Cellar/ncurses/5.9"
git = "https://github.com/jeaye/ncurses-rs.git"
