[package]
name = "minesweeper"
version = "0.0.1"
authors = ["John Foley <john@hisfoleyness.com>"]

[dependencies]
rand = "0.3"

[dependencies.rustspec_assertions]
path = "/Users/jfoley/Projects/Spectator/rustspec-assertions"
